// DB 연결전 임시 데이터 더미
let data = [
  {
    id: 0,
    title: "HTML/CSS 기초 다지기",
    nextTitle: "JavaScript 입문과 웹 UI개발",
    content:
      "표준 HTML부터 flex/grid 모던 레이아웃, Bootstrap, Sass, CSS 애니메이션 등 웹페이지 디자인과 퍼블리싱에 필요한 모든 내용을 배우실 수 있습니다. 최근 스타트업, 대기업 등에서 적극…",
    price: 75000,
    price1: 130000,
    quantity: 1,
    image: "https://ifh.cc/g/13f2HM.png",
    detailImage: "https://ifh.cc/g/8kfTW7.png",
    pztext: "없음",
    image1: "https://ifh.cc/g/ssAmtL.png",
    sugang: "5870",
    rvrv: "43",
    category: "초급",
  },
  {
    id: 1,
    title: "JavaScript 입문과 웹 UI개발",
    nextTitle: "쉽게 이해하는 JavaScript 객체지향 & ES6 신문법",
    content:
      "실제 웹 UI를 여러개 만들어보며 배워보는 JavaScript 기초 수업입니다. 문법만 쭉 나열하면서 가르치면 재미없어서 강의 끄고 유튜브 보러갈 것이 뻔하니 실무 예제 중심의…",
    price: 78000,
    price1: 165000,
    quantity: 1,
    image: "https://ifh.cc/g/ssAmtL.png",
    detailImage: "https://ifh.cc/g/TFcT2y.png",
    pztext: "- HTML/CSS 기초 지식이 필요합니다.",
    image1: "https://ifh.cc/g/Snlkd5.png",
    sugang: "7203",
    rvrv: "100",
    category: "초급",
  },
  {
    id: 2,
    title: "쉽게 이해하는 JavaScript 객체지향 & ES6 신문법",
    nextTitle: "React 리액트 기초부터 쇼핑몰 프로젝트까지!",
    content:
      " JavaScript ES6 신문법과 객체지향을 배울 수 있는 자바스크립트 심화과정입니다. (기초강의 아님 주의) 여러분이 어려워하던 this, class, prototype, 객체지향 개념과 더불어 spread, arrow, async, Promise,…",
    price: 56000,
    price1: 120000,
    quantity: 1,
    image: "https://ifh.cc/g/Snlkd5.png",
    detailImage: "https://ifh.cc/g/vHhFSQ.jpg",
    pztext:
      "- HTML/CSS 기초 JavaScript 기초 (var, function, if, for 반복문, Array와 Object에 자료 저장하고 수정하는 법, forEach 함수)",
    image1: "https://ifh.cc/g/MLthrr.png",
    sugang: "3875",
    rvrv: "36",
    category: "중급",
  },
  {
    id: 3,
    title: "React 리액트 기초부터 쇼핑몰 프로젝트까지!",
    nextTitle: "Node.js, MongoDB로 2시간 만에 빠르게 웹서비스 만들기",
    content:
      "  리액트 쉽게 설명하기 장인, 코딩애플입니다. '상태관리를 위해 객체를 부모 컴포넌트의 state로부터 props로 받아와서 리턴해주세요' 같은 변태 개발자용어 쓰면서 리액트 어렵게 설명하는 나쁜 사람들이 많아서…",
    price: 83000,
    price1: 170000,
    quantity: 1,
    image: "https://ifh.cc/g/MLthrr.png",
    detailImage: "https://ifh.cc/g/yjytct.jpg",
    pztext:
      "- HTML/CSS 기초 JavaScript 기초 (var let const, function, if else, for, [], {} 자료 다루기)",
    image1: "https://ifh.cc/g/GzWvjM.png",
    sugang: "2836",
    rvrv: "26",
    category: "중급",
  },
  {
    id: 4,
    title: "Node.js, MongoDB로 빠르게 웹서비스 만들기",
    nextTitle: "Next.js로 웹서비스 만들기",
    content:
      "프로그래밍 세계 최고로 쉽게 설명해드리는 코딩애플과 함께라면 웹서비스 제작도 뚝딱입니다. 게시판 하나 만들며 배워보는 Node.js 강의가 신설되었습니다!",
    price: 75000,
    price1: 170000,
    quantity: 1,
    image: "https://ifh.cc/g/GzWvjM.png",
    detailImage: "https://ifh.cc/g/VWQaw1.png",
    pztext:
      "- HTML/CSS 기초 JavaScript 또는 다른 프로그래밍 언어 기초 (var let const, function, if else, for, Array와 Object 자료형, class는 몰라도 됩니다)",
    image1: "https://ifh.cc/g/krLoqY.png",
    sugang: "2836",
    rvrv: "23",
    category: "고급",
  },
  {
    id: 5,
    title: "Next.js로 웹서비스 만들기",
    nextTitle: "HTML/CSS 기초 다지기",
    content:
      "Next.js는 프론트엔드부터 서버까지 만들 수 있는 React기반 프레임워크입니다. 이것만 사용해도 풀스택 웹개발이 가능합니다. ",
    price: 35000,
    price1: 70000,
    quantity: 1,
    image: "https://ifh.cc/g/krLoqY.png",
    detailImage: "https://ifh.cc/g/YqrSTT.png",
    pztext:
      "- HTML/CSS 기초 자바스크립트 기초 (var, if, function, for, array, object)",
    image1: "https://ifh.cc/g/13f2HM.png",
    sugang: "1937",
    rvrv: "18",
    category: "고급",
  },
];
export default data;
