spring:
        
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: scott
    # password 주의 !
    password: TIGER

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#          show_sql: true
      format_sql: true


server:
  port: 9090

